debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.mumy.basicboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/board
    username: chris
    password: thisisTESTpw!@#%&
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true #sql ?? ???
    properties:
      hibernate.format_sql: true #??? ??? ???? ??? ?????? ?????? ?? ??
      hibernate.default_batch_fetch_size: 100 #n+1?? ???? ??
  sql.init.mode: always #??? data.sql ?? (?? ??, ????? ??, ??? ????? ??)
  data:
    rest:
      detection-strategy: annotated
      base-path: /api
  thymeleaf3:
    decoupled-logic: true

---

spring:
  config.activate.on-profile: heroku
  datasource:
    url: ${JAWSDB_URL}
  jpa.hibernate.ddl-auto: create
  sql.init.mode: always


